### ISSUE TITLE
Problems trying to compile omnidome 1.1 on Linux Xubuntu 22.04

### ISSUE THREAD

**Issue by krpovmu** [WilstonOreo/omnidome#50]
I'm trying to compile on Xubuntu 22.04 and always this error appears, Do you have any workaround with this problem?

![image](https://github.com/WilstonOreo/omnidome/assets/103374449/f891a21b-4ade-42be-b5fc-604be1c7d4af)

[ 10%] Building CXX object lib/CMakeFiles/omni.dir/src/proj/Calibration.cpp.o
In file included from /home/shuma/Documents/Bauhaus/03-LinuxDome/OmniDome/omnidome-1.1.0/lib/include/omni/proj/Calibration.h:27,
                 from /home/shuma/Documents/Bauhaus/03-LinuxDome/OmniDome/omnidome-1.1.0/lib/src/proj/Calibration.cpp:21:
/home/shuma/Documents/Bauhaus/03-LinuxDome/OmniDome/omnidome-1.1.0/lib/include/omnic/gl/Framebuffer.h: In member function ‘void omnic::gl::Framebuffer<FORMAT, T>::initialize(int, int)’:
/home/shuma/Documents/Bauhaus/03-LinuxDome/OmniDome/omnidome-1.1.0/lib/include/omnic/gl/Framebuffer.h:81:11: error: there are no arguments to ‘glGenFramebuffers’ that depend on a template parameter, so a declaration of ‘glGenFramebuffers’ must be available [-fpermissive]
   81 |           glGenFramebuffers(1, &fb_);
      |           ^~~~~~~~~~~~~~~~~
/home/shuma/Documents/Bauhaus/03-LinuxDome/OmniDome/omnidome-1.1.0/lib/include/omnic/gl/Framebuffer.h:81:11: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/shuma/Documents/Bauhaus/03-LinuxDome/OmniDome/omnidome-1.1.0/lib/include/omnic/gl/Framebuffer.h:85:11: error: there are no arguments to ‘glFramebufferTexture2D’ that depend on a template parameter, so a declaration of ‘glFramebufferTexture2D’ must be available [-fpermissive]
   85 |           glFramebufferTexture2D(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0,
      |           ^~~~~~~~~~~~~~~~~~~~~~
/home/shuma/Documents/Bauhaus/03-LinuxDome/OmniDome/omnidome-1.1.0/lib/include/omnic/gl/Framebuffer.h:90:11: error: there are no arguments to ‘glGenRenderbuffers’ that depend on a template parameter, so a declaration of ‘glGenRenderbuffers’ must be available [-fpermissive]
   90 |           glGenRenderbuffers(1, &depthRb_);
      |           ^~~~~~~~~~~~~~~~~~
/home/shuma/Documents/Bauhaus/03-LinuxDome/OmniDome/omnidome-1.1.0/lib/include/omnic/gl/Framebuffer.h:91:11: error: there are no arguments to ‘glBindRenderbuffer’ that depend on a template parameter, so a declaration of ‘glBindRenderbuffer’ must be available [-fpermissive]
   91 |           glBindRenderbuffer(GL_RENDERBUFFER, depthRb_);
      |           ^~~~~~~~~~~~~~~~~~
/home/shuma/Documents/Bauhaus/03-LinuxDome/OmniDome/omnidome-1.1.0/lib/include/omnic/gl/Framebuffer.h:92:11: error: there are no arguments to ‘glRenderbufferStorage’ that depend on a template parameter, so a declaration of ‘glRenderbufferStorage’ must be available [-fpermissive]
   92 |           glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH_COMPONENT24, _w,_h);
      |           ^~~~~~~~~~~~~~~~~~~~~
/home/shuma/Documents/Bauhaus/03-LinuxDome/OmniDome/omnidome-1.1.0/lib/include/omnic/gl/Framebuffer.h:96:11: error: there are no arguments to ‘glFramebufferRenderbuffer’ that depend on a template parameter, so a declaration of ‘glFramebufferRenderbuffer’ must be available [-fpermissive]
   96 |           glFramebufferRenderbuffer(GL_FRAMEBUFFER,

**Comment by WilstonOreo** [comment]
Hi, sorry for the late answer. Do you have Qt and OpenGL libraries installed?
